export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const LOADING = "LOADING";
export const SPINNER = "SPINNER";
export const GENERAL_ERROR = "GENERAL_ERROR";
export const USER_EMAIL_VERIFIED = "USER_EMAIL_VERIFIED";


// FUND
export const GET_ALL_FUND = "GET_ALL_FUND";
export const CREATE_FUND_PENDING = "CREATE_FUND_PENDING"
export const CREATE_FUND_SUCCESS = "CREATE_FUND_SUCCESS"
export const CREATE_FUND_FAILED = "CREATE_FUND_FAILED"

//PROFILE
export const CREATE_PROFILE_UPDATE = "CREATE_PROFILE_UPDATE"
export const CREATE_PROFILE_PENDING = "CREATE_PROFILE_PENDING"
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS"
export const CREATE_PROFILE_FAILED = "CREATE_PROFILE_FAILED"